package com.datfusrental.email.template;

import org.springframework.stereotype.Component;

@Component
public class ConfirmationMessage {
	
	public String confTempl(){
		
		String htmlTempl = "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "<meta charset=\"UTF-8\">\r\n"
				+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "<title>Your Booking Confirmation</title>\r\n"
				+ "<style>\r\n"
				+ "@media only screen and (max-width: 768px) {\r\n"
				+ "  .container { width: 100% !important; }\r\n"
				+ "  .col { display: block !important; width: 100% !important; border-right: none !important; border-bottom: 2px dashed #eee !important; margin-bottom: 15px !important; }\r\n"
				+ "  .pass-body { padding: 10px !important; }\r\n"
				+ "  .pass-header { flex-direction: column !important; align-items: flex-start !important; padding: 12px !important; }\r\n"
				+ "  .header, .content, .footer, .regards { padding: 15px !important; }\r\n"
				+ "  .pass { margin: 10px !important; }\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body style=\"font-family:Arial, sans-serif;margin:0;padding:0;background:#f5f6f7;\">\r\n"
				+ "\r\n"
				+ "  <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"background:#f5f6f7;\">\r\n"
				+ "    <tr>\r\n"
				+ "      <td align=\"center\">\r\n"
				+ "\r\n"
				+ "        <table class=\"container\" role=\"presentation\" width=\"900\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"max-width:900px;margin:auto;background:#fff;border-radius:8px;overflow:hidden;border:1px solid #ddd;box-shadow:0 2px 8px rgba(0,0,0,0.1);\">\r\n"
				+ "          <tr>\r\n"
				+ "            <td style=\"background:#ff6a00;color:#fff;padding:15px 20px;font-size:18px;font-weight:bold;\">\r\n"
				+ "              Booking Confirmation\r\n"
				+ "            </td>\r\n"
				+ "          </tr>\r\n"
				+ "\r\n"
				+ "          <tr>\r\n"
				+ "            <td style=\"padding:20px;color:#333;font-size:15px;line-height:1.5;\">\r\n"
				+ "              Dear Customer,<br><br>\r\n"
				+ "              Thank you for using <strong>Rome Your Way</strong> platform for your booking.<br>\r\n"
				+ "              Your booking details are indicated below:\r\n"
				+ "            </td>\r\n"
				+ "          </tr>\r\n"
				+ "\r\n"
				+ "          <!-- Boarding Pass -->\r\n"
				+ "          <tr>\r\n"
				+ "            <td style=\"padding:0 15px 20px;\">\r\n"
				+ "              <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"background:#fff;border:1px solid #ddd;border-radius:8px;box-shadow:0 3px 8px rgba(0,0,0,0.1);\">\r\n"
				+ "                \r\n"
				+ "                <!-- Header -->\r\n"
				+ "                <tr>\r\n"
				+ "                  <td style=\"background:#ff6a00;color:#fff;padding:10px 20px;\">\r\n"
				+ "                    <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td style=\"font-weight:bold;font-size:16px;\">Rome Your Way</td>\r\n"
				+ "                        <td align=\"right\" style=\"font-size:16px;font-weight:bold;\">Booking Ticket</td>\r\n"
				+ "                      </tr>\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td colspan=\"2\" style=\"font-size:14px;padding-top:4px;\">Trill Start Here...</td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </table>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "\r\n"
				+ "                <!-- Body -->\r\n"
				+ "                <tr>\r\n"
				+ "                  <td style=\"padding:20px;\">\r\n"
				+ "                    <table role=\"presentation\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "                      <tr style=\"vertical-align:top;\">\r\n"
				+ "                        \r\n"
				+ "                        <!-- Column 1 -->\r\n"
				+ "                        <td class=\"col\" width=\"33%\" style=\"padding:10px 20px;border-right:3px dashed #eee;\">\r\n"
				+ "                          <h3 style=\"margin:0 0 10px;color:#ff6a00;font-size:16px;\">Trip: Sunset Cruise</h3>\r\n"
				+ "                          <table width=\"100%\" style=\"border-collapse:collapse;\">\r\n"
				+ "                            <tr><td>Cruise Name:</td><td><b>Vihaan</b></td></tr>\r\n"
				+ "                            <tr><td>Activity Date:</td><td><b>12 Dec 2025</b></td></tr>\r\n"
				+ "                            <tr><td>Rep. Location:</td><td><b>Panjim Fery</b></td></tr>\r\n"
				+ "                            <tr><td>Rep. Time:</td><td>08:00 PM</td></tr>\r\n"
				+ "                            <tr><td>Dep. Time:</td><td>08:30 PM</td></tr>\r\n"
				+ "                          </table>\r\n"
				+ "                          <div style=\"background:#fff5ee;border-left:4px solid #ff6a00;padding:8px;margin-top:10px;font-size:13px;\">\r\n"
				+ "                            ⚠️ Gate closes 25 minutes before departure.\r\n"
				+ "                          </div>\r\n"
				+ "                        </td>\r\n"
				+ "\r\n"
				+ "                        <!-- Column 2 -->\r\n"
				+ "                        <td class=\"col\" width=\"33%\" style=\"padding:10px 20px;border-right:3px dashed #eee;\">\r\n"
				+ "                          <h3 style=\"margin:0 0 10px;color:#ff6a00;font-size:16px;\">Reservation Details</h3>\r\n"
				+ "                          <table width=\"100%\" style=\"border-collapse:collapse;\">\r\n"
				+ "                            <tr><td>Name:</td><td>ARSHAD / MOHAMMAD</td></tr>\r\n"
				+ "                            <tr><td>Booking Id:</td><td>RYW1209867859</td></tr>\r\n"
				+ "                            <tr><td>Total Pax:</td><td>10</td></tr>\r\n"
				+ "                            <tr><td>Kids Count:</td><td>5</td></tr>\r\n"
				+ "                            <tr><td>Infant:</td><td>1</td></tr>\r\n"
			
//				+ "                            <tr><td>Boarding:</td><td>2105 Hrs</td></tr>\r\n"
//				+ "                            <tr><td>Departure:</td><td>2150 Hrs</td></tr>\r\n"
//				+ "                            <tr><td>Gate:</td><td>23</td></tr>\r\n"
//				+ "                            <tr><td>Zone:</td><td>3</td></tr>\r\n"
//				+ "                            <tr><td>Seat:</td><td>7E</td></tr>\r\n"
//				+ "                            <tr><td>Seq:</td><td>0079</td></tr>\r\n"
//				+ "                            <tr><td>Services:</td><td>XSAT</td></tr>\r\n"
				+ "                          </table>\r\n"
//				+ "                          <div style=\"background:#fff5ee;border-left:4px solid #ff6a00;padding:8px;margin-top:10px;font-size:13px;\">\r\n"
//				+ "                            Dangerous goods & restricted articles must be declared.\r\n"
//				+ "                          </div>\r\n"
				+ "                        </td>\r\n"
				+ "\r\n"
				+ "                        <!-- Column 3 -->\r\n"
				+ "                        <td class=\"col\" width=\"33%\" style=\"padding:10px 20px;\">\r\n"
				+ "                          <h3 style=\"margin:0 0 10px;color:#ff6a00;font-size:16px;\">Payment Details</h3>\r\n"
				+ "                          <table width=\"100%\" style=\"border-collapse:collapse;\">\r\n"
				+ "                            <tr><td><b>Total Amount:</b></td><td>5000</td></tr>\r\n"
				+ "                            <tr><td><b>Advance Paid:</b></td><td>2000</td></tr>\r\n"
				+ "                            <tr><td><b>Due Amount:</b></td><td>3000</td></tr>\r\n"
				+ "                          </table>\r\n"
				+ "                          <div style=\"height:50px;margin-top:10px;background:repeating-linear-gradient(90deg,#000 0 2px,#fff 2px 6px);position:relative;border-radius:4px;\">\r\n"
				+ "                            <span style=\"position:absolute;bottom:5px;right:10px;color:#fff;font-weight:bold;font-size:12px;\">U1BYMS</span>\r\n"
				+ "                          </div>\r\n"
				+ "                        </td>\r\n"
				+ "\r\n"
				+ "                      </tr>\r\n"
				+ "                    </table>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "\r\n"
				+ "                <!-- Footer -->\r\n"
				+ "                <tr>\r\n"
				+ "                  <td style=\"background:#fafafa;font-size:12px;padding:10px 20px;color:#666;\">\r\n"
				+ "                    <table width=\"100%\">\r\n"
				+ "                      <tr>\r\n"
				+ "                        <td>\"SEE IT, SAY IT, SECURE IT\" - Aviation Security Culture Week.</td>\r\n"
				+ "                        <td align=\"right\">\r\n"
				+ "                          <a href=\"https://www.goindigo.in/hotels\" style=\"color:#ff6a00;text-decoration:none;\">Hotels</a> |\r\n"
				+ "                          <a href=\"https://www.newdelhiairport.in/digiyatra\" style=\"color:#ff6a00;text-decoration:none;\">DigiYatra</a>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                    </table>\r\n"
				+ "                  </td>\r\n"
				+ "                </tr>\r\n"
				+ "\r\n"
				+ "              </table>\r\n"
				+ "            </td>\r\n"
				+ "          </tr>\r\n"
				+ "\r\n"
				+ "          <!-- Regards -->\r\n"
				+ "          <tr>\r\n"
				+ "            <td style=\"padding:20px;font-size:15px;color:#333;\">\r\n"
				+ "              Regards,<br>\r\n"
				+ "              <strong>Team Romeyourway</strong><br>\r\n"
				+ "              +91-771-885-8883\r\n"
				+ "            </td>\r\n"
				+ "          </tr>\r\n"
				+ "\r\n"
				+ "        </table>\r\n"
				+ "\r\n"
				+ "      </td>\r\n"
				+ "    </tr>\r\n"
				+ "  </table>\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n"
				+ "";
				
		return htmlTempl;
	}

}
