package com.datfusrental.enums;

public enum RequestFor {
	ALL,BYCATID,BYTYPE,
	
	BYCATEGORY,BYDATE,CREATEDBY,YESTERDAY,TODAY,TOMORROW,WEEK,MONTH,PUNCHIN,PUNCHOUT,CUSTOM,SEARCH,DROPDOWN,
	
	PREVIOUS_DATE,
	NEXT_DATE,
	NEXT_TO_NEXT_DATE,
	MONTH_FIRST_DATE,
	MONTH_LAST_DATE,
	PICKUP,
	DROP;
}
