package com.datfusrental.pdf;

public class VehiclePaymentReceiptWithGST {
	
	
	public void generateReceipt() {
		
		String hi ="<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"UTF-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <title>Vehicle Payment Receipt</title>\r\n"
				+ "  <style>\r\n"
				+ "    :root {\r\n"
				+ "      --navy: #101827;\r\n"
				+ "      --ink: #182233;\r\n"
				+ "      --muted: #d9dee6;\r\n"
				+ "      --soft: #f7f8fa;\r\n"
				+ "      --table-head: #eef2f6;\r\n"
				+ "      --accent-bg: #dceffc;\r\n"
				+ "      --accent: #006ea8;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    * { box-sizing: border-box; }\r\n"
				+ "\r\n"
				+ "    body {\r\n"
				+ "      margin: 0;\r\n"
				+ "      background: #f4f5f7;\r\n"
				+ "      color: var(--ink);\r\n"
				+ "      font-family: Arial, Helvetica, sans-serif;\r\n"
				+ "      font-size: 14px;\r\n"
				+ "      line-height: 1.45;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .page-meta {\r\n"
				+ "      width: min(1060px, calc(100% - 32px));\r\n"
				+ "      margin: 22px auto 36px;\r\n"
				+ "      display: flex;\r\n"
				+ "      justify-content: space-between;\r\n"
				+ "      color: #111;\r\n"
				+ "      font-size: 13px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .receipt {\r\n"
				+ "      width: min(1060px, calc(100% - 32px));\r\n"
				+ "      margin: 0 auto 44px;\r\n"
				+ "      overflow: hidden;\r\n"
				+ "      background: #fff;\r\n"
				+ "      border-radius: 16px;\r\n"
				+ "      box-shadow: 0 12px 28px rgba(16, 24, 39, .08);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .invoice-header {\r\n"
				+ "      display: grid;\r\n"
				+ "      grid-template-columns: 1fr 330px;\r\n"
				+ "      gap: 32px;\r\n"
				+ "      padding: 25px 36px 20px;\r\n"
				+ "      background: var(--navy);\r\n"
				+ "      color: #fff;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .company h1 {\r\n"
				+ "      margin: 0 0 12px;\r\n"
				+ "      font-size: 27px;\r\n"
				+ "      line-height: 1.15;\r\n"
				+ "      letter-spacing: .2px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .company p {\r\n"
				+ "      margin: 4px 0;\r\n"
				+ "      color: #d9e2f3;\r\n"
				+ "      font-size: 15px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .invoice-summary {\r\n"
				+ "      text-align: right;\r\n"
				+ "      font-size: 15px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .invoice-summary p { margin: 0 0 8px; }\r\n"
				+ "\r\n"
				+ "    .status {\r\n"
				+ "      display: flex;\r\n"
				+ "      align-items: center;\r\n"
				+ "      justify-content: flex-end;\r\n"
				+ "      gap: 10px;\r\n"
				+ "      margin-top: 11px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .badge {\r\n"
				+ "      display: inline-block;\r\n"
				+ "      padding: 8px 13px;\r\n"
				+ "      border-radius: 18px;\r\n"
				+ "      background: var(--accent-bg);\r\n"
				+ "      color: var(--accent);\r\n"
				+ "      font-size: 13px;\r\n"
				+ "      white-space: nowrap;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .content { padding: 18px 36px 0; }\r\n"
				+ "\r\n"
				+ "    section { margin-bottom: 20px; }\r\n"
				+ "\r\n"
				+ "    h2 {\r\n"
				+ "      margin: 0;\r\n"
				+ "      padding-bottom: 9px;\r\n"
				+ "      border-bottom: 2px solid #e1e5eb;\r\n"
				+ "      font-size: 21px;\r\n"
				+ "      line-height: 1.2;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .billing-grid {\r\n"
				+ "      display: grid;\r\n"
				+ "      grid-template-columns: 1fr 1fr;\r\n"
				+ "      gap: 16px 18px;\r\n"
				+ "      margin-top: 16px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .info-card {\r\n"
				+ "      min-height: 82px;\r\n"
				+ "      padding: 16px 19px;\r\n"
				+ "      background: var(--soft);\r\n"
				+ "      border: 1px solid var(--muted);\r\n"
				+ "      border-radius: 9px;\r\n"
				+ "      box-shadow: 0 0 0 1px rgba(217, 222, 230, .25);\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .info-card strong {\r\n"
				+ "      display: block;\r\n"
				+ "      margin-bottom: 2px;\r\n"
				+ "      font-size: 15px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    table {\r\n"
				+ "      width: 100%;\r\n"
				+ "      margin-top: 14px;\r\n"
				+ "      border-collapse: collapse;\r\n"
				+ "      table-layout: fixed;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    th, td {\r\n"
				+ "      padding: 10px 9px;\r\n"
				+ "      border: 1px solid #d8dde5;\r\n"
				+ "      text-align: left;\r\n"
				+ "      vertical-align: top;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    th {\r\n"
				+ "      background: var(--table-head);\r\n"
				+ "      font-weight: 700;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .charges-table {\r\n"
				+ "      font-size: 12px;\r\n"
				+ "      text-align: center;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .charges-table th,\r\n"
				+ "    .charges-table td {\r\n"
				+ "      padding: 8px 5px;\r\n"
				+ "      text-align: center;\r\n"
				+ "      overflow-wrap: anywhere;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .charges-table th:first-child { width: 8.5%; }\r\n"
				+ "    .charges-table th:nth-child(2) { width: 8%; }\r\n"
				+ "    .charges-table th:nth-child(3) { width: 8.5%; }\r\n"
				+ "    .charges-table th:nth-child(4) { width: 8.5%; }\r\n"
				+ "    .charges-table th:nth-child(5) { width: 8.5%; }\r\n"
				+ "    .charges-table th:nth-child(6) { width: 8.5%; }\r\n"
				+ "    .charges-table th:nth-child(7) { width: 8.5%; }\r\n"
				+ "\r\n"
				+ "    .pickup-total {\r\n"
				+ "      margin: 17px 0 0;\r\n"
				+ "      font-size: 17px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .terms {\r\n"
				+ "      margin: 12px 0 3px;\r\n"
				+ "      padding: 0;\r\n"
				+ "      list-style: none;\r\n"
				+ "      font-size: 15px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .terms li { margin: 3px 0; }\r\n"
				+ "    .terms li::before { content: \"• \"; }\r\n"
				+ "    .terms .warning::before { content: \"‼ \"; color: #e02243; }\r\n"
				+ "    .terms a { color: #0000ee; }\r\n"
				+ "\r\n"
				+ "    .footer {\r\n"
				+ "      padding: 26px 20px 28px;\r\n"
				+ "      border-top: 1px solid #d8dde5;\r\n"
				+ "      text-align: center;\r\n"
				+ "      color: #141414;\r\n"
				+ "      font-size: 15px;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .footer p { margin: 3px 0; }\r\n"
				+ "\r\n"
				+ "    @media (max-width: 760px) {\r\n"
				+ "      .invoice-header { grid-template-columns: 1fr; }\r\n"
				+ "      .invoice-summary { text-align: left; }\r\n"
				+ "      .status { justify-content: flex-start; }\r\n"
				+ "      .billing-grid { grid-template-columns: 1fr; }\r\n"
				+ "      .charges-scroll { overflow-x: auto; }\r\n"
				+ "      .charges-table { min-width: 850px; }\r\n"
				+ "      .company h1 { font-size: 22px; }\r\n"
				+ "      .content, .invoice-header { padding-left: 20px; padding-right: 20px; }\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @page {\r\n"
				+ "      size: Letter;\r\n"
				+ "      margin: 10mm;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @media print {\r\n"
				+ "      body { background: #fff; font-size: 11px; }\r\n"
				+ "      .page-meta { display: none; }\r\n"
				+ "      .receipt {\r\n"
				+ "        width: 100%;\r\n"
				+ "        margin: 0;\r\n"
				+ "        border-radius: 10px;\r\n"
				+ "        box-shadow: none;\r\n"
				+ "      }\r\n"
				+ "      .invoice-header { grid-template-columns: 1fr 250px; padding: 16px 24px; }\r\n"
				+ "      .company h1 { font-size: 20px; margin-bottom: 7px; }\r\n"
				+ "      .company p, .invoice-summary { font-size: 11px; }\r\n"
				+ "      .invoice-summary p { margin-bottom: 4px; }\r\n"
				+ "      .badge { padding: 5px 9px; font-size: 10px; }\r\n"
				+ "      .content { padding: 12px 24px 0; }\r\n"
				+ "      section { margin-bottom: 12px; break-inside: avoid; }\r\n"
				+ "      h2 { padding-bottom: 5px; font-size: 15px; }\r\n"
				+ "      .billing-grid { gap: 8px 12px; margin-top: 9px; }\r\n"
				+ "      .info-card { min-height: 58px; padding: 9px 13px; }\r\n"
				+ "      .info-card strong { font-size: 11px; }\r\n"
				+ "      table { margin-top: 8px; }\r\n"
				+ "      th, td { padding: 6px; }\r\n"
				+ "      .charges-table { font-size: 9px; }\r\n"
				+ "      .charges-table th, .charges-table td { padding: 5px 3px; }\r\n"
				+ "      .pickup-total { margin-top: 10px; font-size: 12px; }\r\n"
				+ "      .terms { margin-top: 7px; font-size: 11px; }\r\n"
				+ "      .terms li { margin: 1px 0; }\r\n"
				+ "      .footer { padding: 15px; font-size: 11px; }\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "  <div class=\"page-meta\">\r\n"
				+ "    <span>7/23/26, 9:20 PM</span>\r\n"
				+ "    <span>Arshad_M_26072026</span>\r\n"
				+ "  </div>\r\n"
				+ "\r\n"
				+ "  <main class=\"receipt\">\r\n"
				+ "    <header class=\"invoice-header\">\r\n"
				+ "      <div class=\"company\">\r\n"
				+ "        <h1>MYRAAN RENTALS AND ADVENTURES PVT. LTD.</h1>\r\n"
				+ "        <p>Company ID : U52291GA2024OPC016682</p>\r\n"
				+ "        <p>Address : Unit No. 71/195/A, Sattari, Ward No. 7, Hathwada, Near Marathi School,<br>Valpoi, North Goa, Goa - 403506</p>\r\n"
				+ "        <p>TAX ID : AASCM2597H</p>\r\n"
				+ "        <p>Phone : +91 88283 75421 | Email : sales@myraanrentals.com</p>\r\n"
				+ "        <p>GSTIN : 30AASCM2597H1Z5</p>\r\n"
				+ "      </div>\r\n"
				+ "\r\n"
				+ "      <div class=\"invoice-summary\">\r\n"
				+ "        <p><strong>Invoice No:</strong> 7845273233</p>\r\n"
				+ "        <p><strong>Invoice Date:</strong> 26/07/2026</p>\r\n"
				+ "        <p><strong>Payment Terms:</strong> P/A</p>\r\n"
				+ "        <p><strong>Due Date:</strong> 25/07/2026</p>\r\n"
				+ "        <p><strong>Place of Supply:</strong> GOA</p>\r\n"
				+ "        <div class=\"status\">\r\n"
				+ "          <span><strong>Status:</strong> Confirmed</span>\r\n"
				+ "          <span class=\"badge\">Advance Received</span>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </header>\r\n"
				+ "\r\n"
				+ "    <div class=\"content\">\r\n"
				+ "      <section>\r\n"
				+ "        <h2>Billing Information</h2>\r\n"
				+ "        <div class=\"billing-grid\">\r\n"
				+ "          <div class=\"info-card\">\r\n"
				+ "            <strong>Customer Name</strong>\r\n"
				+ "            Arshad M\r\n"
				+ "          </div>\r\n"
				+ "          <div class=\"info-card\">\r\n"
				+ "            <strong>Phone</strong>\r\n"
				+ "            +91 7845273233\r\n"
				+ "          </div>\r\n"
				+ "          <div class=\"info-card\">\r\n"
				+ "            <strong>Company Name &amp; GSTIN</strong>\r\n"
				+ "          </div>\r\n"
				+ "          <div class=\"info-card\">\r\n"
				+ "            <strong>Address</strong>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </section>\r\n"
				+ "\r\n"
				+ "      <section>\r\n"
				+ "        <h2>Schedule Details</h2>\r\n"
				+ "        <table>\r\n"
				+ "          <thead>\r\n"
				+ "            <tr>\r\n"
				+ "              <th>Pickup Scheduled</th>\r\n"
				+ "              <th>Drop Scheduled</th>\r\n"
				+ "            </tr>\r\n"
				+ "          </thead>\r\n"
				+ "          <tbody>\r\n"
				+ "            <tr>\r\n"
				+ "              <td>26/07/2026, 08:30 | Cola</td>\r\n"
				+ "              <td>29/07/2026, 17:00 | Palolem</td>\r\n"
				+ "            </tr>\r\n"
				+ "          </tbody>\r\n"
				+ "        </table>\r\n"
				+ "      </section>\r\n"
				+ "\r\n"
				+ "      <section>\r\n"
				+ "        <h2>Charges Breakdown</h2>\r\n"
				+ "        <div class=\"charges-scroll\">\r\n"
				+ "          <table class=\"charges-table\">\r\n"
				+ "            <thead>\r\n"
				+ "              <tr>\r\n"
				+ "                <th>Description</th>\r\n"
				+ "                <th>Qty</th>\r\n"
				+ "                <th>Duration</th>\r\n"
				+ "                <th>Per day rent</th>\r\n"
				+ "                <th>Pick &amp; drop</th>\r\n"
				+ "                <th>Discount</th>\r\n"
				+ "                <th>Taxable Amount</th>\r\n"
				+ "                <th>CGST</th>\r\n"
				+ "                <th>SGST</th>\r\n"
				+ "                <th>Total</th>\r\n"
				+ "                <th>Advance Paid</th>\r\n"
				+ "                <th>Balance Due</th>\r\n"
				+ "              </tr>\r\n"
				+ "            </thead>\r\n"
				+ "            <tbody>\r\n"
				+ "              <tr>\r\n"
				+ "                <td>BMW 3 Series Automatic-SD</td>\r\n"
				+ "                <td>1</td>\r\n"
				+ "                <td>4 day(s)</td>\r\n"
				+ "                <td>₹20000</td>\r\n"
				+ "                <td>₹0</td>\r\n"
				+ "                <td>₹1000</td>\r\n"
				+ "                <td>₹79000</td>\r\n"
				+ "                <td>₹7110</td>\r\n"
				+ "                <td>₹7110</td>\r\n"
				+ "                <td>₹93220</td>\r\n"
				+ "                <td>₹25220</td>\r\n"
				+ "                <td>₹68000</td>\r\n"
				+ "              </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "          </table>\r\n"
				+ "        </div>\r\n"
				+ "        <p class=\"pickup-total\"><strong>Total amount to be paid at pickup (including balance &amp; deposit):</strong> ₹88000</p>\r\n"
				+ "      </section>\r\n"
				+ "\r\n"
				+ "      <section>\r\n"
				+ "        <h2>Terms &amp; Conditions</h2>\r\n"
				+ "        <ul class=\"terms\">\r\n"
				+ "          <li>Balance Due mentioned is excluding refundable deposit: ₹20000</li>\r\n"
				+ "          <li>Standard Rental Timings: 09:00 AM - 09:00 AM</li>\r\n"
				+ "          <li>Valid driving license &amp; one original ID required for renting</li>\r\n"
				+ "          <li>Vehicle cannot be used for interstate travel</li>\r\n"
				+ "          <li>Fuel Policy: Reserved To Reserved</li>\r\n"
				+ "          <li>Total amount is exclusive of any toll &amp; parking charges</li>\r\n"
				+ "          <li class=\"warning\">PLEASE CARRY CASH FOR BALANCE PAYMENT 🙏 🚫 NO UPI / 🚫 NO CARD</li>\r\n"
				+ "          <li>Check additional T&amp;Cs here <a href=\"#\" onclick=\"return false;\">terms-and-condition</a></li>\r\n"
				+ "        </ul>\r\n"
				+ "      </section>\r\n"
				+ "    </div>\r\n"
				+ "\r\n"
				+ "    <footer class=\"footer\">\r\n"
				+ "      <p>This is a computer generated invoice and does not require a signature.</p>\r\n"
				+ "      <p>Thank you for choosing MYRAAN RENTALS AND ADVENTURES GOA PVT. LTD..</p>\r\n"
				+ "    </footer>\r\n"
				+ "  </main>\r\n"
				+ "</body>\r\n"
				+ "</html>";
	}

}
